version:  '3'

services:
  api:
    image: node:14.18.0-alpine3.11
    container_name: api-marlon
    restart: always
    command: "npm run start"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3333:3333'